name = "GoodsteinPA"
defaultTargets = ["GoodsteinPA"]

[[lean_lib]]
name = "GoodsteinPA"

[[require]]
name = "Foundation"
git = "https://github.com/FormalizedFormalLogic/Foundation.git"
rev = "master"
